package com.destinym.dubbotools.dal.model;

import lombok.*;
import lombok.experimental.SuperBuilder;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class App extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.app_id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.path
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.package_name
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.port
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.project_id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long projectId;
}