package com.destinym.dubbotools.dal.model;

import lombok.*;
import lombok.experimental.SuperBuilder;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class StrategyProjectApp extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_project_app.id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_project_app.app_id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_project_app.strategy_project_id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long strategyProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy_project_app.ip
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String ip;
}