package com.destinym.dubbotools.dal.model;

import lombok.*;
import lombok.experimental.SuperBuilder;

import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class Strategy extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.id
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.name
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.description
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.owner
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.type
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.sync_status
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private String syncStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.create_date
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column strategy.update_date
     *
     * @mbg.generated Wed Aug 21 17:55:24 CST 2019
     */
    private Date updateDate;
}